dataset:
  name: breizh
model:
  name: upssits
  num_classes: 9
  input_dim: 13
  num_steps: 45
  num_proto_per_class: 1
  learn_weights: False
training:
  device: cuda
  loss: recons
  batch_size: 4
  n_workers: 4
  optimizer:
    lr: 1.0e-3
  scheduler:
    factor: 0.1
    patience: 5
    threshold: 0.0001
  n_epochs: 10
  print_step: 500
  valid_step: 10000
  check_cluster_interval: 100
  rdm_seed: 621
  visualizer_port: 8889
  pretrained:
  resume: