dataset:
  name: pastis
  train_fold: [1, 2, 3, 4, 5]
  val_fold: [4]
  test_fold: [5]
  use_ndvi: False
model:
  name: kmeans
  num_classes: 19
  num_prototypes: 32
  input_dim: 10
  num_steps: 406
  learn_weights: False
  # num_proto_per_class: 1
training:
  device: cuda
  loss: recons
  batch_size: 4
  n_workers: 4
  optimizer:
    lr: 1.0e-3
  scheduler:
    factor: 0.1
    patience: 2
    threshold: 0.001
  n_epochs: 20
  print_step: 250
  valid_step: 250
  check_cluster_step: 200
  rdm_seed: 621
  visualizer_port: 8889
  pretrained:
  resume: