dataset:
  name: pastis
  train_fold: [1, 2, 3]
  val_fold: [4]
  test_fold: [5]
  use_ndvi: False
model:
  name: means
  num_classes: 19
  input_dim: 10
  num_steps: 406
  filtering: none
  sigma: 7
training:
  device: cuda
  loss: recons
  batch_size: 4
  n_workers: 4
  n_epochs: 1
  optimizer:
    lr: 1.0e-3
  scheduler:
    factor: 0.1
    patience: 5
    threshold: 0.0001
  rdm_seed: 621
  visualizer_port: 8889
  pretrained:
  resume: