dataset:
  name: ts2c
model:
  name: agrisits
  input_dim: 9
  num_steps: 363
  num_classes: 16
  num_prototypes: 16
  feature_size: 128
  supervised: True
  amplitude: 0.5
  init_proto: means
  missing_dates: True
training:
  device: cuda
  batch_size: 4
  n_workers: 4
  optimizer:
    lr: 1.0e-5
  scheduler:
    factor: 0.1
    patience: 2
    threshold: 0.0001
  n_epochs: 10000
  print_step: 500
  valid_step: 5000
  check_cluster_step: 500
  trans_activ: True
  offset_activ: True
  ce_activ: True
  curriculum: [0, 1000000000, 1000000000]
  rdm_seed: 621
  visualizer_port: 8889
  pretrained:
  resume: