dataset:
  name: ts2c
  with_img_id: False
model:
  name: agrisits
  num_classes: 16
  num_prototypes: 16
  input_dim: 9
  num_steps: 363
  feature_size: 128
  learn_weights: False
  init_proto: True
  n_heads: 16
  mlp: [256, 128]
  d_k: 4
  dropout: 0.2
  d_model: 256
  supervised: True
  dataset_name: ts2c
  # num_proto_per_class: 1
training:
  device: cuda
  loss: recons
  batch_size: 4
  n_workers: 4
  optimizer:
    lr: 1.0e-5
  scheduler:
    factor: 0.1
    patience: 2
    threshold: 0.0001
  n_epochs: 300
  print_step: 500
  valid_step: 5000
  check_cluster_step: 500
  trans_activ: True
  offset_activ: True
  scale_activ: False
  ce_activ: False
  curriculum: [0, 6000]
  rdm_seed: 621
  visualizer_port: 8889
  pretrained:
  resume: