dataset:
  name: ts2c
model:
  name: "svm"
  input_dim: 9
  num_classes: 16
  num_steps: 363
training:
  batch_size: 4
  n_epochs: 100
  print_step: 100
  valid_step: 500
  n_workers: 4
  rdm_seed: 621
