dataset:
  name: ts2c
model:
  name: "tapnet"
  input_dim: 9
  num_steps: 363
  num_classes: 16
  layers: [500, 300]
  dropout: 0
  use_lstm: True
  use_cnn: True
  filters: [256, 256, 128]
  dilation: 1
  kernels: [8, 5, 3]
  use_rp: True
  rp_params: [-1, 3]
  lstm_dim: 128
training:
  rdm_seed: 621
  n_workers: 4
  batch_size: 2
  max_iter: 12000
  train_iter: 100
  val_iter: 1000
  optimizer:
    lr: 1.0e-4
    weight_decay: 1.0e-3
  num_epochs: 3000